### ISSUE TITLE
multiple 520 summaries tag look awkward because label repeats

### ISSUE THREAD

**Issue by phette23** [cca/koha_snippets#21]
I hate how the "summary" label repeats for each MARC 520, see on _[Metaphysics : a very short introduction](https://library.cca.edu/cgi-bin/koha/opac-detail.pl?biblionumber=62082)_ for instance:
<img width="730" alt="Screen Shot 2020-05-17 at 18 23 13" src="https://user-images.githubusercontent.com/1024833/82165862-89db6180-986b-11ea-8b88-d783914da1c0.png">

Unfortunately, CSS doesn't solve this because of the way the `-of-type` selectors work. You'd think either of these might work:

```css
.results_summary.summary:nth-of-type(n + 2) .label { display: none; }
/* or */
.results_summary.summary .label { display: none; }
.results_summary.summary:first-of-type .label { display: inline; }
```

They don't because the "type" being referred to is not element that match the selector being modified, but sibling elements. So without counting all the earlier `.results_summary` elements make it impossible to target the few summaries at the end, unless I'm missing something.
